### PR TITLE
Change doc for LET signals. Add doc for uniswapV3, project-in-trends signals. Fix sidebar navigation for signals.

### PR DESCRIPTION
**Pull request by volynvlad**
## Checklist

- [x] My article available in Navigation sidebar and in root article of selected category ([how to do it in README](https://github.com/santiment/academy#add-an-article-into-navigation-sidebar))
- [x]	My article have [metadata](https://github.com/santiment/academy#metadata) (title, description, date when updated and author)
- [x]	All added/updated links in article are exist, images shows correctly

### CODE REVIEW

**Comment by alresharin** [comment]
image
Signals starting page

**Comment by alresharin** [comment]
image
image

New docs.

**Review by peratik — APPROVED** [review]

**Review by Partysun — APPROVED** [review]

**Comment by Partysun** [comment]
Sure the article about the new Univ3 pool creation should be a little bit bigger.

**Comment by volynvlad** [comment]
> Sure the article about the new Univ3 pool creation should be a little bit bigger.

image

**Pull request merged**
